apiVersion: v1
kind: Service
metadata:
  labels:
    app: triton-3gpu
  name: triton-3gpu
  namespace: triton
spec:
  ports:
  - name: grpc-trtis-serving
    port: 8001
    targetPort: 8001
  - name: http-trtis-serving
    port: 8000
    targetPort: 8000
  - name: prometheus-metrics
    port: 8002
    targetPort: 8002
  selector:
    app: triton-3gpu
  type: LoadBalancer

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: triton-1gpu
#   name: triton-1gpu
#   namespace: triton
# spec:
#   ports:
#   - name: grpc-trtis-serving
#     port: 8001
#     targetPort: 8001
#   - name: http-trtis-serving
#     port: 8000
#     targetPort: 8000
#   - name: prometheus-metrics
#     port: 8002
#     targetPort: 8002
#   selector:
#     app: triton-1gpu
#   type: LoadBalancer
# ---